---
version: "3"
services:
 devopsdb:
  
   image: manikantadevops/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: manikantadevops/mynewapp:appimage
   
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
